name: sagebible
description: "A beautiful and simple Bible app for spiritual growth."
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.0-265.0.dev

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management - Riverpod (modern, scalable, testable)
  flutter_riverpod: ^2.5.1
  
  # Routing - GoRouter (official Flutter navigation)
  go_router: ^14.2.7
  
  # Local Storage - SharedPreferences for auth state
  shared_preferences: ^2.3.2
  
  # Animations
  flutter_animate: ^4.5.0
  
  # Share
  share_plus: ^10.1.2
  
  # Google Fonts for beautiful typography
  google_fonts: ^6.2.1
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # Font Awesome Icons for Google icon
  font_awesome_flutter: ^10.7.0
  
  # Supabase - Backend as a Service
  supabase_flutter: ^2.8.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  
  # Flutter Launcher Icons - Generate app icons for all platforms
  flutter_launcher_icons: ^0.13.1
  
  # Flutter Native Splash - Generate native splash screens
  flutter_native_splash: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  
  # Android adaptive icon (optional - for Android 8.0+)
  adaptive_icon_background: "#5B7C99"  # Your blue-gray color
  adaptive_icon_foreground: "assets/icon.png"
  
  # Web
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#5B7C99"
    theme_color: "#5B7C99"
  
  # Windows
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  
  # macOS
  macos:
    generate: true
    image_path: "assets/icon.png"

# Flutter Native Splash Configuration
flutter_native_splash:
  # Background color (your blue-gray)
  color: "#5B7C99"
  
  # Splash image (your icon)
  image: assets/icon.png
  
  # Branding image (optional - shows at bottom)
  # branding: assets/branding.png
  
  # Color for dark mode
  color_dark: "#1E1E1E"
  image_dark: assets/icon.png
  
  # Android 12+ specific settings
  android_12:
    image: assets/icon.png
    color: "#5B7C99"
    image_dark: assets/icon.png
    color_dark: "#1E1E1E"
  
  # Web settings
  web: true
  
  # iOS settings
  ios: true
  
  # Android settings
  android: true
  
  # Fullscreen mode
  fullscreen: true
